import { Storage } from "@google-cloud/storage";
import probe from "probe-image-size";
import type { GalleryDayGroup, GalleryPhoto } from "./types";

export async function getGCSGalleryImages(): Promise<GalleryDayGroup[]> {
  const bucketName = process.env.GCS_BUCKET_NAME || import.meta.env.GCS_BUCKET_NAME;
  const keyBase64 = process.env.GCP_SERVICE_ACCOUNT_KEY || import.meta.env.GCP_SERVICE_ACCOUNT_KEY;

  if (!bucketName) {
    console.error("GCS_BUCKET_NAME must be set when GALLERY_SOURCE=gcs");
    return [];
  }

  // Target size dimensions and suffixes
  const largeWidth = parseInt(process.env.GCS_LARGE_WIDTH || import.meta.env.GCS_LARGE_WIDTH || "1200", 10);
  const largeHeight = parseInt(process.env.GCS_LARGE_HEIGHT || import.meta.env.GCS_LARGE_HEIGHT || "800", 10);
  const thumbSuffix = process.env.GCS_THUMB_SUFFIX || import.meta.env.GCS_THUMB_SUFFIX || "_400x400.webp";
  const largeSuffix = process.env.GCS_LARGE_SUFFIX || import.meta.env.GCS_LARGE_SUFFIX || "_1200x800.webp";
  const isPrivate = (process.env.GCS_PRIVATE_BUCKET || import.meta.env.GCS_PRIVATE_BUCKET) === "true";
  const thumbsNested = (process.env.GCS_THUMBS_NESTED || import.meta.env.GCS_THUMBS_NESTED || "true") === "true";
  
  // Resized folder prefix within the bucket
  const thumbsFolder = process.env.GCS_THUMBS_FOLDER || import.meta.env.GCS_THUMBS_FOLDER || "thumbs";
  const thumbsPrefix = thumbsFolder.endsWith("/") ? thumbsFolder : `${thumbsFolder}/`;

  let storage: Storage;
  if (keyBase64) {
    try {
      const keyJson = Buffer.from(keyBase64, "base64").toString("utf8");
      const credentials = JSON.parse(keyJson);
      storage = new Storage({ credentials });
    } catch (e) {
      console.error("Failed to parse GCP_SERVICE_ACCOUNT_KEY base64, using default credentials:", e);
      storage = new Storage();
    }
  } else {
    storage = new Storage();
  }

  const bucket = storage.bucket(bucketName);

  // List all files in the bucket
  const [files] = await bucket.getFiles();
  const fileNamesSet = new Set(files.map(f => f.name));

  console.log(`GCS Bucket has ${files.length} files. First 20 files:`);
  files.slice(0, 20).forEach(f => console.log(` - ${f.name}`));

  // Filter for image files and parse YYYY-MM-DD date from path
  const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  const imageExtensions = [".jpg", ".jpeg", ".png", ".webp"];

  const photosByDay: Record<string, GalleryPhoto[]> = {};

  // For signed URLs, set expiration to 1 year from now (for static builds)
  const expiresDate = new Date();
  expiresDate.setFullYear(expiresDate.getFullYear() + 1);

  for (const file of files) {
    // Ignore any files that are inside the thumbs folder (whether root or nested)
    if (file.name.startsWith(thumbsPrefix) || file.name.includes(`/${thumbsFolder}/`)) continue;

    const lowerName = file.name.toLowerCase();
    const hasImageExt = imageExtensions.some(ext => lowerName.endsWith(ext));
    if (!hasImageExt) continue;

    const segments = file.name.split("/");
    const dateSegment = segments.find(s => dateRegex.test(s));
    if (!dateSegment) continue;

    // Split parent directory and filename
    const lastSlashIndex = file.name.lastIndexOf("/");
    let dirPart = "";
    let filePart = file.name;
    if (lastSlashIndex !== -1) {
      dirPart = file.name.substring(0, lastSlashIndex + 1);
      filePart = file.name.substring(lastSlashIndex + 1);
    }

    const dotIndex = filePart.lastIndexOf(".");
    const baseName = dotIndex !== -1 ? filePart.substring(0, dotIndex) : filePart;

    // Output files generated by Firebase extension reside in the thumbs folder
    let thumbPath = "";
    let largePath = "";

    if (thumbsNested) {
      // e.g., 2026-07-06/thumbs/SIV_20260706_0007_400x400.webp
      thumbPath = `${dirPart}${thumbsFolder}/${baseName}${thumbSuffix}`;
      largePath = `${dirPart}${thumbsFolder}/${baseName}${largeSuffix}`;
    } else {
      // e.g., thumbs/2026-07-06/SIV_20260706_0007_400x400.webp
      thumbPath = `${thumbsPrefix}${dirPart}${baseName}${thumbSuffix}`;
      largePath = `${thumbsPrefix}${dirPart}${baseName}${largeSuffix}`;
    }

    // Decide whether to use the large optimized/resized version or fall back to original raw file
    const hasLargeResized = fileNamesSet.has(largePath);
    const finalLargePath = hasLargeResized ? largePath : file.name;

    // Construct URLs (signed if private bucket, public storage URL otherwise)
    let srcUrl = "";
    let thumbUrl = "";

    if (isPrivate) {
      try {
        const [largeSigned] = await bucket.file(finalLargePath).getSignedUrl({
          action: "read",
          expires: expiresDate,
        });
        const [thumbSigned] = await bucket.file(thumbPath).getSignedUrl({
          action: "read",
          expires: expiresDate,
        });
        srcUrl = largeSigned;
        thumbUrl = thumbSigned;
      } catch (e) {
        console.warn(`Failed to sign URLs for ${file.name}, falling back to public URLs:`, e);
      }
    }

    if (!srcUrl || !thumbUrl) {
      srcUrl = `https://storage.googleapis.com/${bucketName}/${finalLargePath}`;
      thumbUrl = `https://storage.googleapis.com/${bucketName}/${thumbPath}`;
    }

    let width = largeWidth;
    let height = largeHeight;

    try {
      const dimensions = await probe(srcUrl);
      width = dimensions.width;
      height = dimensions.height;
    } catch (e) {
      console.warn(`Failed to probe image size for ${srcUrl}, using configured default ${largeWidth}x${largeHeight}:`, e);
    }

    if (!photosByDay[dateSegment]) {
      photosByDay[dateSegment] = [];
    }

    photosByDay[dateSegment].push({
      src: srcUrl,
      thumbnailSrc: thumbUrl,
      width,
      height,
      alt: `SIV Match Image - ${dateSegment}`,
    });
  }

  // Format as GalleryDayGroup[] and sort by date descending
  return Object.entries(photosByDay)
    .map(([date, photos]) => ({
      date,
      photos,
    }))
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}
